<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\DeterministicAiLab.Domain\DeterministicAiLab.Domain.csproj" />
    <ProjectReference Include="..\DeterministicAiLab.Contracts\DeterministicAiLab.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
