<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.2" />
		<PackageReference Include="FluentAssertions" Version="8.10.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="Reqnroll" Version="3.3.4" />
		<PackageReference Include="Reqnroll.xUnit" Version="3.3.4" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
		<PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="3.3.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Domain\DeterministicAiLab.Domain\DeterministicAiLab.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Features\**\*.feature">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>		
		</None>
	</ItemGroup>

	<Target Name="CleanReqnrollCache" BeforeTargets="CoreCompile">
		<ItemGroup>
			<FilesToDelete Include="$(IntermediateOutputPath)**\*.feature.cs" />
		</ItemGroup>
		<Delete Files="@(FilesToDelete)" />
	</Target>


</Project>
